'use client'

import { useRef, useMemo, Suspense } from 'react'
import { Canvas, useFrame, useThree } from '@react-three/fiber'
import { Environment, Points, PointMaterial, Float } from '@react-three/drei'
import * as THREE from 'three'

/* ───────────────────────────────────────────────────────────────
   WARM PALETTE — pink / orange / red theme
   ─────────────────────────────────────────────────────────────── */

const WARM = {
  pink: '#F43F5E',
  rose: '#FB7185',
  orange: '#FB923C',
  amber: '#FBBF24',
  magenta: '#EC4899',
  red: '#DC2626',
  cream: '#FFF5F0',
}

/* ───────────────────────────────────────────────────────────────
   SCROLL CHOREOGRAPHY (Apple-style cinematic)
   ───────────────────────────────────────────────────────────────

   Act 1   0.00 – 0.30   Hero       — scattered duplicates drift
   Act 2   0.30 – 0.55   Merge      — cards accelerate toward phone
   Act 3   0.55 – 0.80   Reveal     — camera dollies in on phone
   Act 4   0.80 – 1.00   Settle     — calm orbit
*/

/* ───────────────────────────────────────────────────────────────
   ASSET PATHS — generated by scripts/build-assets.mjs (warm palette)
   ─────────────────────────────────────────────────────────────── */

const PHOTO_ASSETS = [0, 1, 2, 3, 4, 5].map((i) => `/dedup-assets/photo-${i}.png`)
const MUSIC_ASSETS = [0, 1, 2, 3, 4, 5].map((i) => `/dedup-assets/music-${i}.png`)
const VIDEO_ASSETS = [0, 1, 2, 3].map((i) => `/dedup-assets/video-${i}.png`)
const APK_ASSETS = [0, 1, 2, 3, 4, 5].map((i) => `/dedup-assets/apk-${i}.png`)
const CONTACT_ASSETS = [0, 1, 2, 3, 4, 5, 6, 7].map((i) => `/dedup-assets/contact-${i}.png`)
const DOCUMENT_ASSETS = [0, 1, 2, 3].map((i) => `/dedup-assets/document-${i}.png`)
const AI_ASSET = '/dedup-assets/ai-orb.png'

type Category = 'photo' | 'music' | 'video' | 'apk' | 'contact' | 'document' | 'ai'

/* ───────────────────────────────────────────────────────────────
   TEXTURE LOADER CACHE
   ─────────────────────────────────────────────────────────────── */

const textureLoader = new THREE.TextureLoader()
const textureCache = new Map<string, THREE.Texture>()

function loadTexture(path: string): THREE.Texture {
  let tex = textureCache.get(path)
  if (tex) return tex
  tex = textureLoader.load(path, (t) => {
    t.colorSpace = THREE.SRGBColorSpace
    t.anisotropy = 8
    t.needsUpdate = true
  })
  textureCache.set(path, tex)
  return tex
}

const CATEGORY_COLOR: Record<Category, string> = {
  photo: WARM.orange,
  music: WARM.magenta,
  video: WARM.red,
  apk: WARM.amber,
  contact: WARM.pink,
  document: '#F87171',
  ai: WARM.orange,
}

/* ───────────────────────────────────────────────────────────────
   SCATTERED DUPLICATE CARDS
   ─────────────────────────────────────────────────────────────── */

type Card = {
  category: Category
  assetPath: string
  initialPos: [number, number, number]
  targetPos: [number, number, number]
  scale: number
  rotSpeed: [number, number, number]
  phase: number
}

function DuplicateSwarm({ scrollRef }: { scrollRef: React.MutableRefObject<number> }) {
  const group = useRef<THREE.Group>(null!)

  const cards = useMemo<Card[]>(() => {
    const arr: Card[] = []
    const count = 24

    const pools: { category: Category; assets: string[] }[] = [
      { category: 'photo', assets: PHOTO_ASSETS },
      { category: 'music', assets: MUSIC_ASSETS },
      { category: 'video', assets: VIDEO_ASSETS },
      { category: 'apk', assets: APK_ASSETS },
      { category: 'contact', assets: CONTACT_ASSETS },
      { category: 'document', assets: DOCUMENT_ASSETS },
    ]
    const weights = [8, 4, 4, 3, 3, 2]
    const pool: { category: Category; asset: string }[] = []
    pools.forEach((p, i) => {
      for (let j = 0; j < weights[i]; j++) {
        pool.push({ category: p.category, asset: p.assets[j % p.assets.length] })
      }
    })

    for (let i = 0; i < count; i++) {
      const pick = pool[i % pool.length]
      const theta = Math.random() * Math.PI * 2
      const phi = Math.acos(2 * Math.random() - 1)
      const r = 4.8 + Math.random() * 3.2
      const ix = r * Math.sin(phi) * Math.cos(theta)
      const iy = r * Math.sin(phi) * Math.sin(theta)
      const iz = r * Math.cos(phi) - 1
      const angle = (i / count) * Math.PI * 2
      arr.push({
        category: pick.category,
        assetPath: pick.asset,
        initialPos: [ix, iy, iz],
        // Cards converge to a ring AROUND the phone (not into it — phone sits in the middle)
        targetPos: [
          Math.cos(angle) * 2.0,
          Math.sin(angle) * 2.0,
          Math.sin(angle * 2) * 0.4,
        ],
        scale: 0.55 + Math.random() * 0.45,
        rotSpeed: [
          (Math.random() - 0.5) * 0.5,
          (Math.random() - 0.5) * 0.5,
          (Math.random() - 0.5) * 0.5,
        ],
        phase: Math.random() * Math.PI * 2,
      })
    }
    return arr
  }, [])

  useFrame((state) => {
    if (!group.current) return
    const t = state.clock.getElapsedTime()
    const s = scrollRef.current

    const merge = smoothstep(0.25, 0.55, s)

    group.current.rotation.y = t * 0.08 * (1 - merge) + merge * 0.2
    group.current.rotation.x = merge * -0.15

    group.current.children.forEach((child, i) => {
      const data = cards[i]
      if (!data) return
      const mesh = child as THREE.Mesh

      const lerp = merge
      const flutter = 0.22 * (1 - merge)
      mesh.position.x = THREE.MathUtils.lerp(data.initialPos[0], data.targetPos[0], lerp)
        + Math.sin(t * 0.7 + data.phase) * flutter
      mesh.position.y = THREE.MathUtils.lerp(data.initialPos[1], data.targetPos[1], lerp)
        + Math.cos(t * 0.6 + data.phase) * flutter
      mesh.position.z = THREE.MathUtils.lerp(data.initialPos[2], data.targetPos[2], lerp)

      mesh.rotation.x = t * data.rotSpeed[0] * (1 - merge * 0.8) + data.phase
      mesh.rotation.y = t * data.rotSpeed[1] * (1 - merge * 0.8)
      mesh.rotation.z = t * data.rotSpeed[2] * (1 - merge * 0.8)

      // Cards fade during Act 3 reveal but slower than before — we want them
      // orbiting the phone briefly before disappearing
      const fadeOut = smoothstep(0.65, 0.82, s)
      const scale = data.scale * (1 - merge * 0.4) * (1 - fadeOut)
      mesh.scale.setScalar(Math.max(0.0001, scale))

      const mat = mesh.material as THREE.MeshBasicMaterial
      if (mat) mat.opacity = (1 - fadeOut) * 1.0
    })
  })

  return (
    <group ref={group}>
      {cards.map((card, i) => (
        <CardMesh key={i} card={card} />
      ))}
      <Phone />
    </group>
  )
}

function CardMesh({ card }: { card: Card }) {
  const texture = useMemo(() => loadTexture(card.assetPath), [card.assetPath])
  const color = CATEGORY_COLOR[card.category]

  return (
    <mesh position={card.initialPos} scale={card.scale}>
      <planeGeometry args={[1.2, 1.2]} />
      <meshBasicMaterial
        map={texture}
        transparent
        opacity={1}
        side={THREE.DoubleSide}
        toneMapped={false}
      />
      <mesh position={[0, 0, -0.02]} scale={1.08}>
        <planeGeometry args={[1.2, 1.2]} />
        <meshBasicMaterial
          color={color}
          transparent
          opacity={0.22}
          side={THREE.DoubleSide}
          toneMapped={false}
          blending={THREE.AdditiveBlending}
          depthWrite={false}
        />
      </mesh>
    </mesh>
  )
}

/* ───────────────────────────────────────────────────────────────
   3D PHONE — replaces the central crystal
   Rounded body, screen with warm gradient, camera notch, side buttons.
   Scales up during Act 3 reveal, slow rotation in settle.
   ─────────────────────────────────────────────────────────────── */

function Phone() {
  const group = useRef<THREE.Group>(null!)
  const screen = useRef<THREE.Mesh>(null!)

  useFrame((state, delta) => {
    if (!group.current) return
    const t = state.clock.getElapsedTime()
    const s = (state as any).__scrollRef?.current as number | undefined

    // Phone is hidden initially, fades in during merge, full reveal in Act 3
    const reveal = smoothstep(0.35, 0.65, s ?? 0)
    const settle = smoothstep(0.7, 1.0, s ?? 0)

    group.current.visible = reveal > 0.001
    const breath = 1 + Math.sin(t * 1.1) * 0.025 * settle
    group.current.scale.setScalar(reveal * breath * 1.0)

    // Slow continuous rotation
    const rotSpeed = 0.25 + (1 - settle) * 0.3
    group.current.rotation.y += delta * rotSpeed
    group.current.rotation.x = Math.sin(t * 0.3) * 0.08

    // Pulse the screen emissive
    if (screen.current) {
      const mat = screen.current.material as THREE.MeshStandardMaterial
      if (mat) {
        mat.emissiveIntensity = 0.55 + Math.sin(t * 1.8) * 0.18 + reveal * 0.25
      }
    }
  })

  // Phone dimensions (portrait, ~iPhone-ish proportions)
  const W = 1.4
  const H = 2.8
  const D = 0.18
  const radius = 0.22

  return (
    <group ref={group} scale={0.001}>
      {/* ── PHONE BODY (rounded box) ──────────────────── */}
      <RoundedBoxGeometry args={[W, H, D, radius]} color={WARM.pink} metalness={0.7} roughness={0.25} emissive={WARM.red} emissiveIntensity={0.18} />

      {/* ── SCREEN (slightly inset, with warm gradient) ─ */}
      <mesh ref={screen} position={[0, 0, D / 2 + 0.001]}>
        <planeGeometry args={[W - 0.16, H - 0.16]} />
        <meshStandardMaterial
          color={WARM.magenta}
          emissive={WARM.orange}
          emissiveIntensity={0.6}
          metalness={0.1}
          roughness={0.18}
          toneMapped={false}
        />
      </mesh>

      {/* ── SCREEN GLOW (additive halo behind screen) ── */}
      <mesh position={[0, 0, D / 2 - 0.01]} scale={1.08}>
        <planeGeometry args={[W, H]} />
        <meshBasicMaterial
          color={WARM.orange}
          transparent
          opacity={0.35}
          blending={THREE.AdditiveBlending}
          depthWrite={false}
          toneMapped={false}
        />
      </mesh>

      {/* ── CAMERA NOTCH (small pill at top of screen) ── */}
      <mesh position={[0, H / 2 - 0.22, D / 2 + 0.002]}>
        <boxGeometry args={[0.32, 0.07, 0.005]} />
        <meshStandardMaterial color="#1A0608" metalness={0.9} roughness={0.1} />
      </mesh>

      {/* ── SIDE BUTTONS (power + volume) ─────────────── */}
      <mesh position={[W / 2 + 0.005, 0.35, 0]}>
        <boxGeometry args={[0.02, 0.32, 0.06]} />
        <meshStandardMaterial color={WARM.red} metalness={0.7} roughness={0.3} />
      </mesh>
      <mesh position={[-W / 2 - 0.005, 0.45, 0]}>
        <boxGeometry args={[0.02, 0.22, 0.06]} />
        <meshStandardMaterial color={WARM.red} metalness={0.7} roughness={0.3} />
      </mesh>
      <mesh position={[-W / 2 - 0.005, 0.15, 0]}>
        <boxGeometry args={[0.02, 0.22, 0.06]} />
        <meshStandardMaterial color={WARM.red} metalness={0.7} roughness={0.3} />
      </mesh>

      {/* ── CAMERA BUMPS (back, mostly hidden) ────────── */}
      <mesh position={[-0.35, H / 2 - 0.5, -D / 2 - 0.02]}>
        <boxGeometry args={[0.45, 0.45, 0.04]} />
        <meshStandardMaterial color={WARM.red} metalness={0.7} roughness={0.3} />
      </mesh>
      <mesh position={[-0.45, H / 2 - 0.4, -D / 2 - 0.05]}>
        <cylinderGeometry args={[0.07, 0.07, 0.02, 24]} />
        <meshStandardMaterial color="#1A0608" metalness={0.95} roughness={0.05} />
      </mesh>
      <mesh position={[-0.25, H / 2 - 0.6, -D / 2 - 0.05]}>
        <cylinderGeometry args={[0.07, 0.07, 0.02, 24]} />
        <meshStandardMaterial color="#1A0608" metalness={0.95} roughness={0.05} />
      </mesh>
    </group>
  )
}

/* ───────────────────────────────────────────────────────────────
   ROUNDED BOX — small helper for the phone body
   Uses ExtrudeGeometry with rounded rectangle shape
   ─────────────────────────────────────────────────────────────── */

function RoundedBoxGeometry({
  args: [w, h, d, r],
  color,
  metalness,
  roughness,
  emissive,
  emissiveIntensity,
}: {
  args: [number, number, number, number]
  color: string
  metalness: number
  roughness: number
  emissive: string
  emissiveIntensity: number
}) {
  const geo = useMemo(() => {
    const shape = new THREE.Shape()
    const x = -w / 2
    const y = -h / 2
    shape.moveTo(x + r, y)
    shape.lineTo(x + w - r, y)
    shape.quadraticCurveTo(x + w, y, x + w, y + r)
    shape.lineTo(x + w, y + h - r)
    shape.quadraticCurveTo(x + w, y + h, x + w - r, y + h)
    shape.lineTo(x + r, y + h)
    shape.quadraticCurveTo(x, y + h, x, y + h - r)
    shape.lineTo(x, y + r)
    shape.quadraticCurveTo(x, y, x + r, y)
    const geometry = new THREE.ExtrudeGeometry(shape, {
      depth: d,
      bevelEnabled: true,
      bevelThickness: 0.015,
      bevelSize: 0.015,
      bevelSegments: 4,
      curveSegments: 16,
    })
    geometry.center()
    return geometry
  }, [w, h, d, r])

  return (
    <mesh geometry={geo}>
      <meshStandardMaterial
        color={color}
        metalness={metalness}
        roughness={roughness}
        emissive={emissive}
        emissiveIntensity={emissiveIntensity}
      />
    </mesh>
  )
}

/* ───────────────────────────────────────────────────────────────
   AI ORB — orbiting neural-network disc
   ─────────────────────────────────────────────────────────────── */

function AiOrb({ scrollRef }: { scrollRef: React.MutableRefObject<number> }) {
  const ref = useRef<THREE.Mesh>(null!)
  const texture = useMemo(() => loadTexture(AI_ASSET), [])

  useFrame((state) => {
    if (!ref.current) return
    const t = state.clock.getElapsedTime()
    const s = scrollRef.current

    const reveal = smoothstep(0.5, 0.7, s)
    const fadeOut = smoothstep(0.92, 1.0, s)

    ref.current.visible = reveal > 0.01
    const scale = (0.85 + Math.sin(t * 1.5) * 0.06) * reveal * (1 - fadeOut * 0.3)
    ref.current.scale.setScalar(scale)

    // Orbit around the phone
    const orbitAngle = t * 0.4
    ref.current.position.x = Math.cos(orbitAngle) * 2.4
    ref.current.position.y = Math.sin(orbitAngle * 0.8) * 1.5
    ref.current.position.z = Math.sin(orbitAngle) * 2.4

    ref.current.rotation.z = t * 0.3
    ref.current.lookAt(0, 0, 0)

    const mat = ref.current.material as THREE.MeshBasicMaterial
    if (mat) mat.opacity = reveal * (1 - fadeOut * 0.3)
  })

  return (
    <mesh ref={ref} scale={0.001}>
      <planeGeometry args={[2.0, 2.0]} />
      <meshBasicMaterial
        map={texture}
        transparent
        opacity={0}
        side={THREE.DoubleSide}
        toneMapped={false}
        blending={THREE.AdditiveBlending}
        depthWrite={false}
      />
    </mesh>
  )
}

/* ───────────────────────────────────────────────────────────────
   CAMERA RIG — Apple-style cinematic
   ─────────────────────────────────────────────────────────────── */

function CinematicCamera({ scrollRef }: { scrollRef: React.MutableRefObject<number> }) {
  const { camera, pointer } = useThree()
  const targetPos = useRef(new THREE.Vector3(0, 0, 9))
  const targetLook = useRef(new THREE.Vector3(0, 0, 0))

  useFrame((state, delta) => {
    const s = scrollRef.current

    const act1to2 = smoothstep(0.0, 0.55, s)
    const act2to3 = smoothstep(0.55, 0.8, s)
    const act3to4 = smoothstep(0.8, 1.0, s)

    const z =
      9 -
      act1to2 * 2.5 -
      act2to3 * 1.8 -
      act3to4 * -0.5

    const y = 0.6 - act1to2 * 0.6 - act2to3 * 0.3

    const settleOrbit = act3to4
    const orbitAngle = state.clock.getElapsedTime() * 0.15 * settleOrbit
    const ox = Math.sin(orbitAngle) * 0.6 * settleOrbit
    const oy = Math.cos(orbitAngle) * 0.4 * settleOrbit

    const px = pointer.x * 0.4
    const py = pointer.y * 0.25

    targetPos.current.set(ox + px, y + oy + py, z)
    camera.position.lerp(targetPos.current, Math.min(1, delta * 3))

    targetLook.current.set(0, 0, 0)
    const m = new THREE.Matrix4().lookAt(camera.position, targetLook.current, new THREE.Vector3(0, 1, 0))
    const q = new THREE.Quaternion().setFromRotationMatrix(m)
    camera.quaternion.slerp(q, Math.min(1, delta * 4))
  })

  return null
}

/* ───────────────────────────────────────────────────────────────
   STARFIELD
   ─────────────────────────────────────────────────────────────── */

function Starfield() {
  const positions = useMemo(() => {
    const count = 1400
    const arr = new Float32Array(count * 3)
    for (let i = 0; i < count; i++) {
      const r = 22 + Math.random() * 24
      const theta = Math.random() * Math.PI * 2
      const phi = Math.acos(2 * Math.random() - 1)
      arr[i * 3] = r * Math.sin(phi) * Math.cos(theta)
      arr[i * 3 + 1] = r * Math.sin(phi) * Math.sin(theta)
      arr[i * 3 + 2] = r * Math.cos(phi)
    }
    return arr
  }, [])

  const ref = useRef<THREE.Points>(null!)
  useFrame((state) => {
    if (!ref.current) return
    ref.current.rotation.y = state.clock.getElapsedTime() * 0.012
    ref.current.rotation.x = state.clock.getElapsedTime() * 0.006
  })

  return (
    <Points ref={ref} positions={positions} stride={3} frustumCulled={false}>
      <PointMaterial
        transparent
        color={WARM.rose}
        size={0.045}
        sizeAttenuation
        depthWrite={false}
        opacity={0.55}
      />
    </Points>
  )
}

/* ───────────────────────────────────────────────────────────────
   LIGHTS — warm key + pink/orange rim lights
   ─────────────────────────────────────────────────────────────── */

function CinematicLights({ scrollRef }: { scrollRef: React.MutableRefObject<number> }) {
  const keyRef = useRef<THREE.DirectionalLight>(null!)
  const rim1Ref = useRef<THREE.PointLight>(null!)
  const rim2Ref = useRef<THREE.PointLight>(null!)

  useFrame(() => {
    const s = scrollRef.current
    const reveal = smoothstep(0.55, 0.85, s)
    if (keyRef.current) keyRef.current.intensity = 1.2 + reveal * 0.8
    if (rim1Ref.current) rim1Ref.current.intensity = 2.0 + reveal * 2.5
    if (rim2Ref.current) rim2Ref.current.intensity = 2.0 + reveal * 2.5
  })

  return (
    <>
      <ambientLight intensity={0.5} />
      <directionalLight ref={keyRef} position={[5, 6, 6]} intensity={1.2} color="#FFF5F0" />
      <pointLight ref={rim1Ref} position={[-6, 2, -2]} intensity={2.0} color={WARM.pink} />
      <pointLight ref={rim2Ref} position={[6, -2, 2]} intensity={2.0} color={WARM.orange} />
      <pointLight position={[0, 0, 8]} intensity={0.6} color={WARM.magenta} />
    </>
  )
}

/* ───────────────────────────────────────────────────────────────
   UTIL
   ─────────────────────────────────────────────────────────────── */

function smoothstep(edge0: number, edge1: number, x: number) {
  const t = Math.min(1, Math.max(0, (x - edge0) / (edge1 - edge0)))
  return t * t * (3 - 2 * t)
}

/* ───────────────────────────────────────────────────────────────
   SCROLL STATE PROVIDER
   ─────────────────────────────────────────────────────────────── */

function ScrollStateBridge({
  scrollRef,
  children,
}: {
  scrollRef: React.MutableRefObject<number>
  children: React.ReactNode
}) {
  useFrame((state) => {
    ;(state as any).__scrollRef = scrollRef
  })
  return <>{children}</>
}

/* ───────────────────────────────────────────────────────────────
   MAIN SCENE
   ─────────────────────────────────────────────────────────────── */

type SceneProps = {
  scrollRef: React.MutableRefObject<number>
}

export default function DedupScene({ scrollRef }: SceneProps) {
  return (
    <Canvas
      camera={{ position: [0, 0.6, 9], fov: 45, near: 0.1, far: 100 }}
      dpr={[1, 1.75]}
      gl={{ antialias: true, alpha: true, powerPreference: 'high-performance' }}
      style={{ position: 'absolute', inset: 0 }}
    >
      <fog attach="fog" args={['#0F0608', 14, 38]} />

      <Suspense fallback={null}>
        <ScrollStateBridge scrollRef={scrollRef}>
          <CinematicLights scrollRef={scrollRef} />
          <CinematicCamera scrollRef={scrollRef} />

          <Float speed={1.1} rotationIntensity={0.12} floatIntensity={0.4} floatingRange={[-0.08, 0.08]}>
            <DuplicateSwarm scrollRef={scrollRef} />
          </Float>

          <AiOrb scrollRef={scrollRef} />

          <Starfield />
          <Environment preset="sunset" />
        </ScrollStateBridge>
      </Suspense>
    </Canvas>
  )
}
